/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inventory;

import javax.sql.DataSource;
import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.jdbc.DataSourceBuilder;
import org.springframework.context.annotation.Bean;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

@SpringBootApplication
@EnableSwagger2
@MapperScan("inventory.dao")
public class App {

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
        System.out.println(new App().getGreeting());
    }

    @Bean("dataSource")
    public DataSource datasource() {
        return DataSourceBuilder.create()
            .driverClassName("com.mysql.cj.jdbc.Driver")
            .url("jdbc:mysql://localhost:3306/nokia_inventory?useSSL=false")
            .username("nokia")
            .password("nokia")
            .build();
    }
}
