/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package product;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication

public class App {
    public String getGreeting() {
        return "Hello world.";
    }
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
        System.out.println(new App().getGreeting());
    }

}
