/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exception.handler;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.context.request.WebRequest;

@ControllerAdvice
public class App {

   /* @ExceptionHandler({ValidationException.class, })
    public final ResponseEntity<String> handleException(Exception ex, WebRequest request) {
        if (ex instanceof ValidationException) {
            ex.getMessage();

        }
    }*/
}
