spring :
  application: product

server :
  port: 1002

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)

  datasource:
   url: jdbc:mysql://localhost:3306/notes_app?useSSL=false
   username : root
   password : root


  ## Hibernate Properties
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
   properties:
    hibernate:
     dialect : org.hibernate.dialect.MySQL5InnoDBDialect

  # Hibernate ddl auto (create, create-drop, validate, update)
    ddl-auto : update
